### ISSUE TITLE
Add hono example / docs

### ISSUE THREAD

**Issue by treeder** [treeder/rend#15]
https://hono.dev/

**Comment by yashchaddha** [comment]
Hi! I would love to contribute on this issue. Can i please get assigned to this

**Comment by treeder** [comment]
Absolutely! Just fork the repo and make a pull request.

**Comment by yashchaddha** [comment]
Can you please provide me the example/docs?

**Comment by treeder** [comment]
You could copy the example directory and convert this: https://github.com/treeder/rend/blob/main/example/app.js to use hono instead of fastify.
